### ISSUE TITLE
Dungeons are missing chests, spawners, and enemies

### ISSUE THREAD

**Issue by Poikilos** [Poikilos/Enliven#199]
~~configurable? enable in patches/subgame/minetest.server-example.conf if so codermobs has spawner capabilities~~ It was not configurable, but is now, as of Final Minetest 190825

@EliotSeineRoe @HenryNautilus
- [x] (done upstream in Final Minetest 190825) add loot mod ~~to ENLIVEN~~
- [x] (done upstream in Final Minetest 190825 via special node) limit spawning of certain mobs to dungeons ~~apply patch to Bucket Game for mdskeleton and Oerrki spawing. @OldCoder:~~
  - The loot mod works well in ENLIVEN (along with its mods which are mostly from Bucket Game)
  - compare loot mod to treasurer and find out why treasurer has far more code but seems to do less (requires separate registration for loot to be in multiple groups unlike loot).
  - Limiting skeletons and Oerrki mostly to dungeons is a good step that allows deferring the broader issue which may be tricky. See modified spawning for them in EnlivenMinetest/Bucket_Game-branches/codermobs-dungeon-balancing-190815-vs-190812  
- [x] (done upstream in Final Minetest 190825) put spawners in dungeon elsewhere ~~"doors"~~ to circumvent loot api limitation ~~Consider using `darkage:ors` as a `spawn_by` param (occurs in cobblestone dungeons--so far `default:cobble` is over and down from it, though there is `default:mossycobble` nearby also on the floor) (tested using 190824)~~
  - find out how darkage places `darkage:ors` as dungeon "doors" (door-sized formations on wall) and consider adding something else there if removing darkage from enliven.

**Comment by slopsbucket** [comment]
HenryNautilus is a little bit "old school". :)

Onya Henry!

We once again return to Animals_modpack.

It generates bookcases with loot and Dungeon Masters in dungeons. Dungeon Masters are particularly nasty, they throw fireballs at you and when you get in close they switch to melee attack, they are healed by fire so if they're near lava you've got real trouble.

**Comment by poikilos** [comment]
This is apparently not configurable yet, according to `grep -r Bucket_Game -e "minetest.setting"`

**Comment by slopsbucket** [comment]
I think both tsm_pyramids and mobf provide good templates of how this should be done, ie, they both work.

**Comment by poikilos** [comment]
@OldCoder:
- loot works well in ENLIVEN (along with its mods which are mostly from Bucket Game)
- Limiting skeletons and Oerrki mostly to dungeons is a good step that allows deferring the broader issue which may be tricky. See modified spawning for them in EnlivenMinetest/Bucket_Game-branches/codermobs-dungeon-balancing-190815-vs-190812

**Comment by poikilos** [comment]
@HenryNautilus @EliotSeineRoe done in Final Minetest [190825](https://minetest.org/changes.html#190825)!
