### ISSUE TITLE
Some mobs walk underwater (known for: dog, wolf)

### ISSUE THREAD

**Issue by Poikilos** [Poikilos/Enliven#238]
@HenryNautilus

**Comment by poikilos** [comment]
@HenryNautilus  Is it working now? Bucket_Game addressed this upstream

**Comment by slopsbucket** [comment]
I thought I fixed that a week or so ago. They also don't walk on top of the water any more either.

Skeletons are different, they don't drown because they're already dead. :)

All of those mobs need looking at properly soon, there's still a lot of little errors in there.
