### ISSUE TITLE
Delete poikilos/tsm_pyramids and use reinstated upstream

### ISSUE THREAD

**Issue by Poikilos** [Poikilos/Enliven#77]
* The tsm_pyramids fork by xisd is available again at <https://framagit.org/xisd-minetest/tsm_pyramid> (xisd had deleted his GitHub account).
  Compare to https://github.com/poikilos/tsm_pyramids and see whether that repo can be deleted.

**Comment by poikilos** [comment]
not needed since pyramids are in Bucket_Game

**Comment by poikilos** [comment]
@OldCoder rebased the Bucket_Game copy of tsm_pyramids on the upstream version 1.0.0 (for the next release after 200227)
